### ISSUE TITLE
private messages not working

### ISSUE THREAD

**Issue by tommasobenatti** [Artuto/deluxechat-velocity-bridge#1]
Hi, private messages are not bridging, it says that the player is offline

**Comment by Artuto** [comment]
You are completely sure the player's name you're typing in is online?

**Comment by tommasobenatti** [comment]
yea, is online on the other server, the chat links correctly, but when I try to send a private message it doesn't even appear on the tabcomplete

**Comment by Artuto** [comment]
Are you sure that player is online IN the same Velocity instance and that they connected through Velocity?

**Comment by tommasobenatti** [comment]
yea, 100% sure

**Comment by tommasobenatti** [comment]
bump?

**Comment by Artuto** [comment]
Is BungeeCord messaging enabled in your config?

![image](https://user-images.githubusercontent.com/9273973/147888452-57b1e470-65bf-484a-b344-dfb0007fadf9.png)

**Comment by tommasobenatti** [comment]
oh, I didn't saw it, my fault
